version: 2.0

# Default actions to perform on each Emacs version
default: &default-steps
  steps:
    - restore_cache:
        name: Restore Emacs deps
        keys:
          - cask-{{ checksum "Cask" }}
    - run:
        name: Update APT packages
        command: apt-get update
    - run:
        name: Install prerequisites
        command: apt-get install -y openjdk-17-jre
    - checkout
    - run:
        # Note: this makes it hard to reproduce builds but easier to spot incompatibilities with
        # newer PlantUML releases. Current trade off seems acceptable.
        name: Download the latest PlantUML release
        command: sh ./bin/download-plantuml.sh
    - run:
        name: Download Cask deps
        command: cask install
    - run:
        name: Run the tests
        command: make unit
    - save_cache:
        name: Restore Emacs deps
        key: cask-{{ checksum "Cask" }}
        paths:
          - ~/.emacs.d

# Enumerated list of Emacs versions
jobs:
  test-emacs-25:
    docker:
      - image: silex/emacs:25-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-emacs-26:
    docker:
      - image: silex/emacs:26-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-emacs-27:
    docker:
      - image: silex/emacs:27-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-emacs-28:
    docker:
      - image: silex/emacs:28-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-emacs-29:
    docker:
      - image: silex/emacs:29-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-emacs-30:
    docker:
      - image: silex/emacs:30-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-emacs-master:
    docker:
      - image: silex/emacs:master-ci-cask
        entrypoint: bash
    <<: *default-steps

  test-plantuml-server:
    docker:
      - image: silex/emacs:30-ci-cask
        entrypoint: bash
      ## Server listens at port 8080
      - image: plantuml/plantuml-server:jetty
    steps:
      - checkout
      - restore_cache:
          name: Restore Emacs deps
          keys:
            - cask-{{ checksum "Cask" }}
      - run:
          name: Download Cask deps
          command: cask install
      - run:
          name: Run the tests
          command: make integration
      - run:
          name: Download Cask deps
          command: cask install
      - save_cache:
          name: Restore Emacs deps
          key: cask-{{ checksum "Cask" }}
          paths:
            - ~/.emacs.d

# Executing in parallel
workflows:
  version: 2
  ci-test-matrix:
    jobs:
      - test-emacs-25
      - test-emacs-26
      - test-emacs-27
      - test-emacs-28
      - test-emacs-29
      - test-emacs-30
      - test-emacs-master
  server:
    jobs:
      - test-plantuml-server
